name: 'dprint-check-action'
description: 'Run `dprint check` on your source code'
author: 'thomaseizinger'
inputs:
  dprint-version:
    description: 'Specific dprint version to use (ex. 0.30.3)'
    required: false
    default: ''
  config-path:
    description: 'Specific dprint config to use (ex. dprint.json)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install dprint
      shell: bash
      run: |
        curl -fsSL https://dprint.dev/install.sh | sh -s ${{ inputs.dprint-version }} > /dev/null 2>&1
        echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
    - name: Check formatting
      shell: bash
      if: "${{ inputs.config-path == '' }}"
      run: ~/.dprint/bin/dprint check
    - name: Check formatting with config
      shell: bash
      if: "${{ inputs.config-path != '' }}"
      run: ~/.dprint/bin/dprint check --config '${{ inputs.config-path }}'
branding:
  icon: 'check-circle'
  color: 'gray-dark'
