#!/usr/bin/env -S deno run -A
import $ from "@david/dax";
import { action, concat, conditions, defineInputs, expr, hashFiles, isLinting, step } from "@david/gagen";

const inputs = defineInputs({
  "dprint-version": {
    description: "Specific dprint version to use (ex. 0.30.3)",
    required: false,
    default: "",
  },
  "config-path": {
    description: "Specific dprint config to use (ex. dprint.json)",
    required: false,
    default: "",
  },
  args: {
    description: "Additional arguments to pass to dprint check",
    required: false,
    default: "",
  },
  cache: {
    description: "Cache dprint's plugins and incremental state in the GitHub Actions cache (ex. true)",
    required: false,
    default: "false",
  },
});

const cacheEnabled = inputs.cache.equals("true");
const cacheDir = expr("env.DPRINT_CACHE_DIR");

const install = step({
  name: "Install dprint",
  run: [
    `curl -fsSL https://dprint.dev/install.sh | sh -s ${inputs["dprint-version"]} > /dev/null 2>&1`,
    `if [ "$RUNNER_OS" = "Windows" ]; then`,
    `  cygpath -w "$HOME/.dprint/bin" >> "$GITHUB_PATH"`,
    `else`,
    `  echo "$HOME/.dprint/bin" >> "$GITHUB_PATH"`,
    `fi`,
  ],
});

// the hash of the config file the check will use, or of every config file in
// the repo when dprint discovers the config itself (a remote config url can't
// be hashed, so that falls back to the repo's config files too)
const configPath = inputs["config-path"];
const configHash = configPath.notEquals("")
  .and(configPath.startsWith("http").not())
  .then(hashFiles(configPath))
  .else(hashFiles("**/dprint.json", "**/dprint.jsonc", "**/.dprint.json", "**/.dprint.jsonc"));

const prepareCache = step({
  name: "Prepare dprint cache",
  id: "cache-key",
  if: cacheEnabled,
  env: { CONFIG_HASH: configHash },
  run: [
    `# respect a directory the user already set so later steps share the same cache`,
    `if [ -z "\${DPRINT_CACHE_DIR:-}" ]; then`,
    `  cache_dir="$RUNNER_TEMP/dprint-cache"`,
    `  if [ "$RUNNER_OS" = "Windows" ]; then`,
    `    cache_dir=$(cygpath -w "$cache_dir")`,
    `  fi`,
    `  echo "DPRINT_CACHE_DIR=$cache_dir" >> "$GITHUB_ENV"`,
    `fi`,
    `echo "platform-prefix=dprint-cache-$RUNNER_OS-$RUNNER_ARCH" >> "$GITHUB_OUTPUT"`,
    `echo "config-prefix=dprint-cache-$RUNNER_OS-$RUNNER_ARCH-$CONFIG_HASH" >> "$GITHUB_OUTPUT"`,
  ],
  outputs: ["platform-prefix", "config-prefix"] as const,
});

// the incremental state changes every run, so each run saves under a unique
// key and restores by prefix: first a previous run of this job with the same
// config, then any job with the same config, then anything for this platform;
// dprint validates the restored plugins and incremental state itself, so a
// stale match is always safe
const configPrefix = prepareCache.outputs["config-prefix"];
const restoreCache = step({
  name: "Restore dprint cache",
  id: "restore-cache",
  if: cacheEnabled,
  uses: "actions/cache/restore@v5",
  with: {
    path: cacheDir,
    key: concat(configPrefix, "-", expr("github.job"), "-", expr("github.run_id"), "-", expr("github.run_attempt")),
    "restore-keys": [
      concat(configPrefix, "-", expr("github.job"), "-"),
      concat(configPrefix, "-"),
      concat(prepareCache.outputs["platform-prefix"], "-"),
    ].join("\n"),
  },
  outputs: ["cache-hit", "cache-primary-key", "cache-matched-key"] as const,
}).dependsOn(prepareCache);

const check = step({
  name: "Check formatting",
  env: { CONFIG_PATH: configPath },
  run: `~/.dprint/bin/dprint check \${CONFIG_PATH:+--config "$CONFIG_PATH"} ${inputs.args}`,
}).dependsOn(install).comesAfter(restoreCache);

// save even when the check fails so the compiled plugins and the incremental
// state of the correctly formatted files carry over
const saveCache = step({
  name: "Save dprint cache",
  if: conditions.status.always()
    .and(cacheEnabled)
    .and(restoreCache.outputs["cache-primary-key"].notEquals(""))
    .and(restoreCache.outputs["cache-hit"].notEquals("true")),
  uses: "actions/cache/save@v5",
  with: {
    path: cacheDir,
    key: restoreCache.outputs["cache-primary-key"],
  },
}).comesAfter(check);

action({
  name: "dprint-check-action",
  description: "Run `dprint check` on your source code",
  author: "the dprint authors",
  inputs,
  outputs: {
    "cache-matched-key": {
      description: "Key of the cache entry that was restored, if any",
      value: restoreCache.outputs["cache-matched-key"],
    },
  },
  defaults: { run: { shell: "bash" } },
  steps: [install, restoreCache, check, saveCache],
  branding: { icon: "check-circle", color: "gray-dark" },
}).writeOrLint({
  filePath: new URL("../../action.yml", import.meta.url),
  header: "# GENERATED BY ./.github/workflows/action.ts -- DO NOT DIRECTLY EDIT",
});

if (!isLinting) {
  await $`dprint fmt --log-level=warn action.yml`;
}
