#!/usr/bin/env -S deno run -A
import $ from "jsr:@david/dax@0.45.0";
import { concat, defineMatrix, expr, hashFiles, isLinting, job, step, workflow } from "jsr:@david/gagen@0.6.0";

const matrix = defineMatrix({
  os: ["ubuntu-latest", "macOS-latest", "windows-latest"],
});

// a copy of dprint.json with a comment unique to this run, so the cache jobs
// get a cache key hash no other run has and can assert on their own entries
const cacheTestConfig = "cache-test.json";
const runUniqueId = concat(expr("github.run_id"), "-", expr("github.run_attempt"));
const createCacheTestConfig = [
  "{",
  `  echo "// ${runUniqueId}"`,
  "  cat dprint.json",
  `} > ${cacheTestConfig}`,
];
const createPoorlyFormattedFile = `echo '{"a": 1, "b": 2}' > poorly-formatted.json`;

const checkout = step({
  uses: "actions/checkout@v7",
});
// windows checks out with crlf line endings by default, which dprint flags
const checkoutWithLf = step({
  name: "Use LF line endings",
  run: [
    "git config --global core.autocrlf false",
    "git config --global core.eol lf",
  ],
}, checkout);

// === style job ===

const styleJob = job("style", {
  runsOn: matrix.os,
  strategy: { matrix },
  defaults: { run: { shell: "bash" } },
  steps: step.dependsOn(checkoutWithLf)(
    {
      name: "Check formatting latest",
      uses: "./",
    },
    {
      name: "Check formatting specific version",
      uses: "./",
      with: { "dprint-version": "0.49.1" },
    },
    {
      name: "Check formatting specific config",
      uses: "./",
      with: { "config-path": "dprint.json" },
    },
    {
      name: "Check formatting specific version and config",
      uses: "./",
      with: { "dprint-version": "0.49.1", "config-path": "dprint.json" },
    },
    {
      name: "Check formatting with cache",
      uses: "./",
      with: { cache: true },
    },
    {
      name: "Check formatting with cache and specific version",
      uses: "./",
      with: { cache: true, "dprint-version": "0.49.1" },
    },
    {
      name: "Make poorly-formatted json file",
      run: createPoorlyFormattedFile,
    },
    {
      name: "Check formatting with excludes",
      uses: "./",
      with: { args: "--excludes poorly-formatted.json" },
    },
    {
      name: "Later steps can run dprint with the same cache",
      run: [
        `test -n "$DPRINT_CACHE_DIR"`,
        `test -d "$DPRINT_CACHE_DIR/plugins"`,
        "dprint --version",
      ],
    },
  ),
});

// === cache jobs ===

const cachePrimeCheck = step({
  name: "Check formatting (expected to fail)",
  id: "check",
  uses: "./",
  continueOnError: true,
  with: { cache: true, "config-path": cacheTestConfig },
});

const cachePrimeJob = job("cache-prime", {
  runsOn: matrix.os,
  strategy: { matrix },
  defaults: { run: { shell: "bash" } },
  steps: step.dependsOn(checkoutWithLf)(
    {
      name: "Create unique config and poorly-formatted file",
      run: [...createCacheTestConfig, createPoorlyFormattedFile],
    },
    cachePrimeCheck,
    {
      name: "Verify the check failed",
      run: `test "${expr("steps.check.outcome")}" = "failure"`,
    },
  ),
});

const cacheHitCheck = step({
  name: "Check formatting",
  id: "check",
  uses: "./",
  with: { cache: true, "config-path": cacheTestConfig },
  outputs: ["cache-matched-key"] as const,
});

const cacheHitJob = job("cache-hit", {
  runsOn: matrix.os,
  strategy: { matrix },
  needs: [cachePrimeJob],
  defaults: { run: { shell: "bash" } },
  steps: step.dependsOn(checkoutWithLf)(
    {
      name: "Recreate unique config",
      run: createCacheTestConfig,
    },
    cacheHitCheck,
    {
      name: "Verify the cache saved by the failed cache-prime job was restored",
      env: {
        MATCHED_KEY: cacheHitCheck.outputs["cache-matched-key"],
        EXPECTED_KEY: concat(
          "dprint-cache-",
          expr("runner.os"),
          "-",
          expr("runner.arch"),
          "-",
          hashFiles(cacheTestConfig),
          "-",
          cachePrimeJob.id,
          "-",
          runUniqueId,
        ),
      },
      run: [
        `echo "matched key: $MATCHED_KEY"`,
        `echo "expected:    $EXPECTED_KEY"`,
        `test "$MATCHED_KEY" = "$EXPECTED_KEY"`,
      ],
    },
  ),
});

// === lint job ===

const lintJob = job("lint", {
  runsOn: "ubuntu-latest",
  steps: step.dependsOn(checkout)(
    step({
      uses: "denoland/setup-deno@v2",
    }),
    step({
      name: "Lint CI generation",
      run: "./.github/workflows/ci.ts --lint",
    }),
  ),
});

// === generate ===

workflow({
  name: "CI",
  on: ["push", "pull_request"],
  jobs: [
    styleJob,
    cachePrimeJob,
    cacheHitJob,
    lintJob,
  ],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header: "# GENERATED BY ./ci.ts -- DO NOT DIRECTLY EDIT",
});

if (!isLinting) {
  await $`dprint fmt --log-level=warn "**/*.yml"`;
}
