name: CI

on: [push, pull_request]

jobs:
  style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Use LF line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Check formatting latest
        uses: ./

      - name: Check formatting specific version
        uses: ./
        with:
          dprint-version: 0.30.3

      - name: Check formatting specific config
        uses: ./
        with:
          dprint-config-path: 'dprint-another.json'

      - name: Check formatting old version and specific config
        uses: ./
        with:
          # config schema `projectType` is removed since 0.15.0
          # ref: https://github.com/dprint/dprint/commit/f41d1fa50d68fd0d0c1a7def9fb6cbae25b0ddc6
          dprint-version: 0.15.0
          dprint-config-path: 'dprint-another.json'
