name: CI

on: [push, pull_request]

jobs:
  style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Use LF line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Check formatting latest
        uses: ./

      - name: Check formatting specific version
        uses: ./
        with:
          dprint-version: 0.30.3

      - name: Check formatting specific config
        uses: ./
        with:
          config-path: 'dprint.json'

      - name: Check formatting specific version and config
        uses: ./
        with:
          dprint-version: 0.30.3
          config-path: 'dprint.json'
