name: CI

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check formatting
        uses: ./
