name: CI

on:
  push:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check formatting latest
        uses: ./
        with:
          dprint-version: latest

      - name: Check formatting specific version
        uses: ./
        with:
          dprint-version: 0.17.0
